"""
Integration Tests for Gemini Service with Mocked API
"""

import pytest
from unittest.mock import Mock, patch, MagicMock
from app.services.gemini_service import (
    gemini_interpretation_service,
    GeminiConfigurationError,
    GeminiAPIError
)
from app.ml.prediction_normalizer import prediction_normalizer
from app.services.clinical_context import clinical_context_builder
from app.services.gemini_prompts import gemini_prompt_builder


class TestGeminiIntegration:
    """Integration tests for the full Gemini interpretation flow."""
    
    @patch('app.services.gemini_service.genai')
    def test_signal_prediction_interpretation(self, mock_genai):
        """Test end-to-end signal prediction interpretation with mocked API."""
        # Setup mock
        mock_client = MagicMock()
        mock_response = MagicMock()
        mock_response.text = '''{
  "summary": "The model detected ECG patterns suggestive of myocardial infarction.",
  "primary_finding": "ECG patterns suggestive of myocardial infarction",
  "confidence_interpretation": "The model showed relatively strong classification signal.",
  "possible_clinical_associations": [
    {
      "name": "Coronary artery disease",
      "explanation": "May be associated with coronary artery disease",
      "relationship": "possible_association"
    }
  ],
  "why_flagged": "The model detected ST segment changes.",
  "what_it_means": "This may indicate possible myocardial ischemia.",
  "limitations": "ECG findings alone cannot definitively establish myocardial infarction.",
  "disclaimer": "This interpretation is generated by an AI system for educational and research purposes."
}'''
        mock_client.generate_content.return_value = mock_response
        mock_genai.configure.return_value = None
        mock_genai.GenerativeModel.return_value = mock_client
        
        # Initialize service
        gemini_interpretation_service.api_key = "test-api-key"
        gemini_interpretation_service._initialize_client()
        
        # Create normalized prediction
        raw_prediction = {
            "prediction": "Myocardial Infarction",
            "prediction_code": "MI",
            "confidence": 0.86,
            "probabilities": {
                "NORM": 0.04,
                "MI": 0.86,
                "STTC": 0.32,
                "CD": 0.05,
                "HYP": 0.04
            },
            "all_predictions": {"MI": True},
            "model_version": "1.0",
            "processing_time": 0.15
        }
        
        normalized = prediction_normalizer.normalize_signal_prediction(raw_prediction)
        
        # Interpret
        interpretation = gemini_interpretation_service.interpret_prediction(normalized)
        
        # Verify
        assert interpretation is not None
        assert "summary" in interpretation
        assert "primary_finding" in interpretation
        assert "possible_clinical_associations" in interpretation
        assert "safety_metadata" in interpretation
        assert interpretation["safety_metadata"]["interpretation_scope"] == "ecg_finding"
    
    @patch('app.services.gemini_service.genai')
    def test_image_prediction_interpretation(self, mock_genai):
        """Test end-to-end image prediction interpretation with mocked API."""
        # Setup mock
        mock_client = MagicMock()
        mock_response = MagicMock()
        mock_response.text = '''{
  "summary": "The model detected a ventricular premature beat pattern.",
  "primary_finding": "Ventricular premature beat (PVC) pattern",
  "confidence_interpretation": "The model showed relatively strong classification signal.",
  "possible_clinical_associations": [
    {
      "name": "Ventricular ectopy",
      "explanation": "May be associated with ventricular ectopy",
      "relationship": "possible_association"
    }
  ],
  "why_flagged": "The model detected abnormal QRS morphology.",
  "what_it_means": "This may indicate ventricular ectopy.",
  "limitations": "Single-beat analysis does not assess overall cardiac rhythm.",
  "disclaimer": "This interpretation is generated by an AI system for educational and research purposes."
}'''
        mock_client.generate_content.return_value = mock_response
        mock_genai.configure.return_value = None
        mock_genai.GenerativeModel.return_value = mock_client
        
        # Initialize service
        gemini_interpretation_service.api_key = "test-api-key"
        gemini_interpretation_service._initialize_client()
        
        # Create normalized prediction
        raw_prediction = {
            "prediction": "PVC",
            "prediction_code": "V",
            "confidence": 0.91,
            "probabilities": {"V": 0.91},
            "model_name": "EfficientNet-B0",
            "model_version": "1.0",
            "processing_time": 0.089
        }
        
        interpretation_data = {
            "dominant_group": "Ventricular",
            "group_probabilities": {"Ventricular": 0.91}
        }
        
        normalized = prediction_normalizer.normalize_image_prediction(raw_prediction, interpretation_data)
        
        # Interpret
        interpretation = gemini_interpretation_service.interpret_prediction(normalized)
        
        # Verify
        assert interpretation is not None
        assert "summary" in interpretation
        assert "primary_finding" in interpretation
        assert interpretation["safety_metadata"]["interpretation_scope"] == "ecg_finding"
    
    @patch('app.services.gemini_service.genai')
    def test_low_confidence_interpretation(self, mock_genai):
        """Test interpretation with low confidence."""
        # Setup mock
        mock_client = MagicMock()
        mock_response = MagicMock()
        mock_response.text = '''{
  "summary": "The model showed limited classification confidence.",
  "primary_finding": "Possible ST/T changes",
  "confidence_interpretation": "The model does not strongly favor a single category.",
  "possible_clinical_associations": [],
  "why_flagged": "Low confidence prediction.",
  "what_it_means": "The result should be interpreted cautiously.",
  "limitations": "Low confidence requires clinical correlation.",
  "disclaimer": "This interpretation is generated by an AI system for educational and research purposes."
}'''
        mock_client.generate_content.return_value = mock_response
        mock_genai.configure.return_value = None
        mock_genai.GenerativeModel.return_value = mock_client
        
        # Initialize service
        gemini_interpretation_service.api_key = "test-api-key"
        gemini_interpretation_service._initialize_client()
        
        # Create low confidence prediction
        raw_prediction = {
            "prediction": "ST/T Changes",
            "prediction_code": "STTC",
            "confidence": 0.35,
            "probabilities": {"ST/T Changes": 0.35},
            "all_predictions": {"ST/T Changes": True},
            "model_version": "1.0",
            "processing_time": 0.12
        }
        
        normalized = prediction_normalizer.normalize_signal_prediction(raw_prediction)
        
        # Interpret
        interpretation = gemini_interpretation_service.interpret_prediction(normalized)
        
        # Verify
        assert interpretation is not None
        assert "confidence_interpretation" in interpretation
    
    @patch('app.services.gemini_service.genai')
    def test_multi_label_prediction(self, mock_genai):
        """Test interpretation with multi-label prediction."""
        # Setup mock
        mock_client = MagicMock()
        mock_response = MagicMock()
        mock_response.text = '''{
  "summary": "The model detected multiple relevant ECG patterns.",
  "primary_finding": "Myocardial infarction with ST/T changes",
  "confidence_interpretation": "The model detected multiple relevant findings.",
  "possible_clinical_associations": [
    {
      "name": "Coronary artery disease",
      "explanation": "May be associated with coronary artery disease",
      "relationship": "possible_association"
    }
  ],
  "why_flagged": "Multiple abnormal patterns detected.",
  "what_it_means": "This may indicate complex cardiac pathology.",
  "limitations": "Multiple findings require comprehensive clinical evaluation.",
  "disclaimer": "This interpretation is generated by an AI system for educational and research purposes."
}'''
        mock_client.generate_content.return_value = mock_response
        mock_genai.configure.return_value = None
        mock_genai.GenerativeModel.return_value = mock_client
        
        # Initialize service
        gemini_interpretation_service.api_key = "test-api-key"
        gemini_interpretation_service._initialize_client()
        
        # Create multi-label prediction
        raw_prediction = {
            "prediction": "Myocardial Infarction",
            "prediction_code": "MI",
            "confidence": 0.86,
            "probabilities": {
                "NORM": 0.04,
                "MI": 0.86,
                "STTC": 0.72,
                "CD": 0.08,
                "HYP": 0.04
            },
            "all_predictions": {"MI": True, "STTC": True},
            "model_version": "1.0",
            "processing_time": 0.15
        }
        
        normalized = prediction_normalizer.normalize_signal_prediction(raw_prediction)
        
        # Interpret
        interpretation = gemini_interpretation_service.interpret_prediction(normalized)
        
        # Verify
        assert interpretation is not None
        assert "summary" in interpretation
    
    @patch('app.services.gemini_service.genai')
    def test_invalid_json_response(self, mock_genai):
        """Test handling of invalid JSON response."""
        # Setup mock with invalid JSON
        mock_client = MagicMock()
        mock_response = MagicMock()
        mock_response.text = "This is not valid JSON"
        mock_client.generate_content.return_value = mock_response
        mock_genai.configure.return_value = None
        mock_genai.GenerativeModel.return_value = mock_client
        
        # Initialize service
        gemini_interpretation_service.api_key = "test-api-key"
        gemini_interpretation_service._initialize_client()
        
        # Create prediction
        raw_prediction = {
            "prediction": "Normal",
            "prediction_code": "NORM",
            "confidence": 0.85,
            "probabilities": {"Normal": 0.85},
            "all_predictions": {"Normal": True},
            "model_version": "1.0",
            "processing_time": 0.1
        }
        
        normalized = prediction_normalizer.normalize_signal_prediction(raw_prediction)
        
        # Should raise error
        with pytest.raises(GeminiAPIError) as exc_info:
            gemini_interpretation_service.interpret_prediction(normalized)
        
        assert "validation failed" in str(exc_info.value).lower()
    
    @patch('app.services.gemini_service.genai')
    def test_missing_fields_response(self, mock_genai):
        """Test handling of response with missing required fields."""
        # Setup mock with incomplete JSON
        mock_client = MagicMock()
        mock_response = MagicMock()
        mock_response.text = '''{
  "summary": "Test summary"
}'''
        mock_client.generate_content.return_value = mock_response
        mock_genai.configure.return_value = None
        mock_genai.GenerativeModel.return_value = mock_client
        
        # Initialize service
        gemini_interpretation_service.api_key = "test-api-key"
        gemini_interpretation_service._initialize_client()
        
        # Create prediction
        raw_prediction = {
            "prediction": "Normal",
            "prediction_code": "NORM",
            "confidence": 0.85,
            "probabilities": {"Normal": 0.85},
            "all_predictions": {"Normal": True},
            "model_version": "1.0",
            "processing_time": 0.1
        }
        
        normalized = prediction_normalizer.normalize_signal_prediction(raw_prediction)
        
        # Should raise error
        with pytest.raises(GeminiAPIError) as exc_info:
            gemini_interpretation_service.interpret_prediction(normalized)
        
        assert "validation failed" in str(exc_info.value).lower()
    
    @patch('app.services.gemini_service.genai')
    def test_gemini_api_failure(self, mock_genai):
        """Test handling of Gemini API failure."""
        # Setup mock to raise exception
        mock_genai.configure.side_effect = Exception("API connection failed")
        
        # Initialize should fail
        gemini_interpretation_service.api_key = "test-api-key"
        
        with pytest.raises(GeminiConfigurationError):
            gemini_interpretation_service._initialize_client()
    
    @patch('app.services.gemini_service.genai')
    def test_unsafe_response_rejected(self, mock_genai):
        """Test that unsafe response is rejected by safety validator."""
        # Setup mock with unsafe response
        mock_client = MagicMock()
        mock_response = MagicMock()
        mock_response.text = '''{
  "summary": "You have myocardial infarction.",
  "primary_finding": "Myocardial infarction",
  "confidence_interpretation": "High confidence",
  "possible_clinical_associations": [],
  "why_flagged": "ST elevation",
  "what_it_means": "You definitely have a heart attack",
  "limitations": "None",
  "disclaimer": "Not a diagnosis"
}'''
        mock_client.generate_content.return_value = mock_response
        mock_genai.configure.return_value = None
        mock_genai.GenerativeModel.return_value = mock_client
        
        # Initialize service
        gemini_interpretation_service.api_key = "test-api-key"
        gemini_interpretation_service._initialize_client()
        
        # Create prediction
        raw_prediction = {
            "prediction": "Myocardial Infarction",
            "prediction_code": "MI",
            "confidence": 0.86,
            "probabilities": {"MI": 0.86},
            "all_predictions": {"MI": True},
            "model_version": "1.0",
            "processing_time": 0.15
        }
        
        normalized = prediction_normalizer.normalize_signal_prediction(raw_prediction)
        
        # Should raise error due to unsafe language
        with pytest.raises(GeminiAPIError) as exc_info:
            gemini_interpretation_service.interpret_prediction(normalized)
        
        assert "validation failed" in str(exc_info.value).lower()
