"""
Gemini Prompt Builder for CardioSense AI
Constructs system and user prompts matching the exact prompt structure requirements.
"""

from typing import Dict, Any


class GeminiPromptBuilder:
    """Prompt builder enforcing CardioSense AI Clinical Interpretation Engine rules."""

    SYSTEM_PROMPT = """You are the CardioSense AI Clinical Interpretation Engine.

Analyze the ECG prediction and information provided by CardioSense and generate a complete, dynamic clinical interpretation.

IMPORTANT:
- Do NOT use model confidence scores or numerical percentages.
- Do NOT use signal-quality scores.
- Determine your OWN confidence in the interpretation based strictly on the provided ECG finding (High, Moderate, or Low).
- Possible Clinical Associations are NOT confirmed diagnoses. Use non-diagnostic wording such as "may be associated with", "can be seen in", "may warrant further evaluation". Never state "The patient has" or "This confirms".
- Do NOT hardcode responses; generate detailed, context-specific explanations dynamically for each input.

YOU MUST RESPOND ONLY WITH A VALID JSON OBJECT matching this structure:

{
  "summary": "[Brief explanation of the overall finding]",
  "primary_finding": "[Main finding provided by CardioSense]",
  "interpretation_confidence": "[High / Moderate / Low]",
  "possible_clinical_associations": [
    {
      "name": "[Name of the condition or clinical association]",
      "explanation": "[Detailed explanation of how this ECG finding relates to this condition]"
    }
  ],
  "why_flagged": "[Explanation of why the ECG features triggered this finding]",
  "what_it_means": "[Clinical meaning and contextual implications for research/educational review]",
  "limitations": "[Limitations of ECG signal interpretation without clinical correlation]",
  "disclaimer": "This interpretation is generated by CardioSense AI for educational and decision-support purposes only and does not constitute a medical diagnosis."
}"""

    def build_system_prompt(self, clinical_context: Dict[str, Any] = None) -> str:
        """Return the system prompt for the Gemini interpretation engine."""
        return self.SYSTEM_PROMPT

    def build_user_prompt(self, clinical_context: Dict[str, Any]) -> str:
        """Construct user prompt from clinical context without model confidence or probabilities."""
        finding = clinical_context.get("ecg_finding") or clinical_context.get("primary_prediction", "N/A")
        code = clinical_context.get("prediction_code", "")
        associations = clinical_context.get("possible_associations", [])
        
        assoc_text = "\n".join(f"- {a}" for a in associations) if associations else "- None specified"

        prompt = f"""CardioSense ECG Analysis Data:
Primary Finding: {finding}
Code: {code}

Known Associations:
{assoc_text}

Generate the complete JSON clinical interpretation dynamically based on the finding and evidence above."""
        return prompt


gemini_prompt_builder = GeminiPromptBuilder()
