from typing import Dict, Any, List

# Human-readable names for the 15 ECG subclasses predicted by the trained model.
# The raw class codes are the keys returned by the model (config `class_mapping`).
SUBCLASS_LABELS: Dict[str, str] = {
    "N": "Normal Beat",
    "L": "Left Bundle Branch Block Beat",
    "R": "Right Bundle Branch Block Beat",
    "e": "Atrial Escape Beat",
    "j": "Junctional Escape Beat",
    "A": "Atrial Premature Beat",
    "J": "Junctional Premature Beat",
    "S": "Supraventricular Premature Beat",
    "aa": "Aberrated Atrial Premature Beat",
    "V": "Ventricular Premature Beat (PVC)",
    "E": "Ventricular Escape Beat",
    "F": "Fusion Beat",
    "Q": "Unclassifiable Beat",
    "p": "Paced Beat",
    "f": "Fusion/Paced Beat",
}

# Order of subclasses matching the trained model's class index order.
SUBCLASS_ORDER: List[str] = ["N", "L", "R", "e", "j", "A", "J", "S", "aa", "V", "E", "F", "Q", "p", "f"]

# Higher-level ECG groups and the subclasses that compose them. Group probabilities
# are the sum of the corresponding subclass probabilities.
GROUP_DEFINITIONS: Dict[str, List[str]] = {
    "Normal": ["N", "L", "R", "e", "j"],
    "Supraventricular": ["A", "J", "S", "aa"],
    "Ventricular": ["V", "E"],
    "Fusion": ["F"],
    "Other/Unclassifiable": ["Q", "p", "f"],
}

GROUP_ORDER: List[str] = [
    "Normal",
    "Supraventricular",
    "Ventricular",
    "Fusion",
    "Other/Unclassifiable",
]

GROUP_DESCRIPTIONS: Dict[str, str] = {
    "Normal": "normal and benign variants (normal, bundle branch block, escape beats)",
    "Supraventricular": "supraventricular (upper-chamber) ectopy including premature beats",
    "Ventricular": "ventricular (lower-chamber) ectopy including premature ventricular contractions",
    "Fusion": "fusion beats",
    "Other/Unclassifiable": "paced, paced-fusion, and unclassifiable beats",
}

MEDICAL_DISCLAIMER = (
    "This is an AI-assisted ECG pattern assessment generated by a deep learning model. "
    "It is not a standalone medical diagnosis and does not replace evaluation by a "
    "qualified healthcare professional. Model probabilities are pattern-similarity scores "
    "from the trained model and are not calibrated to disease probability, cardiac risk, "
    "or clinical outcome."
)

EMERGENCY_SAFETY = (
    "If you are experiencing chest pain, severe shortness of breath, fainting, severe "
    "dizziness, or any other acute concerning symptoms, seek urgent medical attention "
    "immediately. An AI-based ECG pattern assessment cannot determine whether an "
    "emergency is occurring, and a low-risk-looking result does not mean you are safe."
)

UNCERTAINTY_NOTE = (
    "The predicted ECG pattern has substantial uncertainty. Professional ECG "
    "interpretation is recommended rather than relying on this result alone."
)

# Recommendation generated from the actual predicted (highest-probability) subclass.
SUBCLASS_RECOMMENDATIONS: Dict[str, str] = {
    "N": (
        "The model's highest prediction is a normal beat pattern, and no abnormal beat "
        "pattern is dominant in the model output. Continue routine clinical follow-up "
        "when appropriate. This result does not rule out other cardiac conditions."
    ),
    "L": (
        "Review of the ECG by a qualified healthcare professional is recommended. A "
        "standard clinical ECG / 12-lead ECG and clinical context may be required for "
        "proper interpretation."
    ),
    "R": (
        "Professional ECG review and clinical correlation are recommended. A standard "
        "clinical ECG / 12-lead ECG may be appropriate depending on symptoms and clinical "
        "history."
    ),
    "e": (
        "Professional ECG review is recommended, particularly if the finding is "
        "persistent or associated with symptoms."
    ),
    "j": (
        "Professional ECG interpretation and clinical correlation are recommended, "
        "particularly when symptoms are present."
    ),
    "A": (
        "Clinical review is recommended if the finding is recurrent, frequent, or "
        "associated with symptoms such as palpitations, dizziness, or fainting."
    ),
    "J": (
        "Professional ECG review and clinical correlation are recommended, especially "
        "if the finding is recurrent or symptomatic."
    ),
    "S": (
        "Professional ECG review is recommended if the finding is recurrent or "
        "symptomatic. Further clinical evaluation may be appropriate."
    ),
    "aa": (
        "Professional ECG review is recommended because proper interpretation requires "
        "the original ECG and clinical context."
    ),
    "V": (
        "Professional medical review and clinical ECG assessment are recommended, "
        "especially if the finding is frequent or associated with chest discomfort, "
        "fainting, significant dizziness, or shortness of breath."
    ),
    "E": (
        "Prompt professional ECG evaluation is recommended because this pattern requires "
        "clinical context and should not be interpreted from the AI image result alone."
    ),
    "F": (
        "Professional ECG interpretation is recommended because proper assessment "
        "requires clinical ECG context."
    ),
    "Q": (
        "The ECG beat pattern could not be confidently classified. Consider uploading a "
        "clearer ECG image or obtaining professional interpretation of the original ECG."
    ),
    "p": (
        "Professional ECG review is recommended, particularly if the person has a "
        "cardiac pacemaker or known pacing history."
    ),
    "f": (
        "Professional ECG interpretation is recommended because proper interpretation "
        "may require knowledge of pacing status and the original ECG recording."
    ),
}

HIGH_CONFIDENCE = 0.60
MODERATE_CONFIDENCE = 0.40
MEANINGFUL_ABNORMAL_PROB = 0.10
CONCENTRATED_TOP_PROB = 0.50
COMPETING_PROB = 0.10


def verify_distribution(probabilities: Dict[str, float]) -> Dict[str, Any]:
    """Verify the 15 subclass probabilities form a single normalized distribution."""
    total = sum(probabilities.values())
    is_normalized = abs(total - 1.0) <= 1e-2
    return {"is_normalized": is_normalized, "total": round(total, 6)}


def compute_group_probabilities(probabilities: Dict[str, float]) -> Dict[str, float]:
    """Aggregate subclass probabilities into the five higher-level ECG groups."""
    groups = {}
    for group, members in GROUP_DEFINITIONS.items():
        groups[group] = round(sum(probabilities.get(cls, 0.0) for cls in members), 6)
    return groups


def human_label(raw_class: str) -> str:
    return SUBCLASS_LABELS.get(raw_class, raw_class)


def subclass_group(raw_class: str) -> str:
    for group, members in GROUP_DEFINITIONS.items():
        if raw_class in members:
            return group
    return "Other/Unclassifiable"


def build_subclass_results(
    probabilities: Dict[str, float], group_probabilities: Dict[str, float]
) -> List[Dict[str, Any]]:
    """Per-subclass structured results, sorted highest to lowest probability."""
    results = []
    for raw_class, probability in probabilities.items():
        group = subclass_group(raw_class)
        results.append({
            "raw_class": raw_class,
            "human_readable_label": human_label(raw_class),
            "probability": round(probability, 6),
            "group": group,
            "group_probability": group_probabilities.get(group, 0.0),
        })
    results.sort(key=lambda r: r["probability"], reverse=True)
    return results


def dominant_group(group_probabilities: Dict[str, float]) -> str:
    return max(GROUP_ORDER, key=lambda g: group_probabilities.get(g, 0.0))


def _fmt_pct(value: float) -> str:
    return f"{value * 100:.1f}%"


def build_pattern_summary(
    primary_prediction: str,
    primary_confidence: float,
    group_probabilities: Dict[str, float],
    subclass_results: List[Dict[str, Any]],
) -> str:
    """User-friendly summary based on the actual complete probability distribution."""
    if not subclass_results:
        return "An ECG pattern assessment could not be generated from the available data."

    top = subclass_results[0]
    primary_label = top["human_readable_label"]
    top_prob = top["probability"]
    dom = dominant_group(group_probabilities)
    dom_prob = group_probabilities.get(dom, 0.0)

    competing = [
        r for r in subclass_results[1:]
        if r["probability"] >= COMPETING_PROB and r["raw_class"] != primary_prediction
    ]

    parts: List[str] = []

    parts.append(
        f"The model's highest-probability prediction is {primary_label} at "
        f"{_fmt_pct(top_prob)}."
    )
    parts.append(
        f"The strongest higher-level ECG pattern group is {dom} at {_fmt_pct(dom_prob)}."
    )

    if top_prob >= CONCENTRATED_TOP_PROB:
        parts.append(
            "The model output is concentrated on a single subclass, indicating a "
            "relatively focused prediction."
        )
    else:
        parts.append(
            "The model output is distributed across several subclasses rather than "
            "concentrated on a single one, so the prediction carries meaningful "
            "uncertainty."
        )

    if competing:
        names = ", ".join(
            f"{r['human_readable_label']} ({_fmt_pct(r['probability'])})"
            for r in competing[:3]
        )
        parts.append(
            f"Other subclasses with meaningful probability include: {names}."
        )

    if top_prob < MODERATE_CONFIDENCE or top_prob < CONCENTRATED_TOP_PROB:
        parts.append(UNCERTAINTY_NOTE)
    else:
        parts.append(
            "Even with a relatively focused result, this is an AI-based pattern "
            "assessment and not a medical diagnosis. Professional ECG interpretation "
            "is recommended when clinical decisions are involved."
        )

    return " ".join(parts)


def build_recommended_next_steps(
    primary_prediction: str,
    primary_confidence: float,
    subclass_results: List[Dict[str, Any]],
    group_probabilities: Dict[str, float],
) -> List[str]:
    """Recommendation generated from the actual predicted subclass and full distribution."""
    steps: List[str] = []

    top = subclass_results[0] if subclass_results else None
    top_prob = top["probability"] if top else 0.0
    distributed = top is not None and top_prob < CONCENTRATED_TOP_PROB
    clvl = "low" if primary_confidence < HIGH_CONFIDENCE else (
        "moderate" if primary_confidence < HIGH_CONFIDENCE else "moderate"
    )
    if primary_confidence < MODERATE_CONFIDENCE:
        clvl = "low"
    elif primary_confidence < HIGH_CONFIDENCE:
        clvl = "moderate"
    else:
        clvl = "high"

    if clvl == "low" or distributed:
        steps.append(UNCERTAINTY_NOTE)

    recommendation = SUBCLASS_RECOMMENDATIONS.get(
        primary_prediction,
        "Professional ECG interpretation is recommended rather than relying on this AI "
        "assessment alone.",
    )
    steps.append(recommendation)

    steps.append(
        "Do not use this AI assessment to decide medication, dosage, treatment, or any "
        "medical procedure. Any such decision must be made by a qualified healthcare "
        "professional."
    )
    steps.append(EMERGENCY_SAFETY)
    return steps


def interpret_image(
    probabilities: Dict[str, float],
    prediction: str,
    confidence: float,
) -> Dict[str, Any]:
    """Full interpretation pipeline over the model's 15-class probability output.

    Returns a structured report object used by both the web page and the PDF so that
    the two never disagree. The raw class is retained internally but is not exposed
    as a user-facing primary label.
    """
    dist = verify_distribution(probabilities)
    group_probs = compute_group_probabilities(probabilities)
    subclass_results = build_subclass_results(probabilities, group_probs)
    dom = dominant_group(group_probs)
    primary_label = human_label(prediction)

    pattern_summary = build_pattern_summary(
        primary_prediction=prediction,
        primary_confidence=confidence,
        group_probabilities=group_probs,
        subclass_results=subclass_results,
    )
    next_steps = build_recommended_next_steps(
        primary_prediction=prediction,
        primary_confidence=confidence,
        subclass_results=subclass_results,
        group_probabilities=group_probs,
    )

    return {
        "distribution_verified": dist["is_normalized"],
        "distribution_total": dist["total"],
        "raw_class": prediction,
        "human_readable_label": primary_label,
        "primary_prediction": prediction,
        "primary_label": primary_label,
        "primary_confidence": round(confidence, 6),
        "dominant_group": dom,
        "group_probabilities": group_probs,
        "subclass_results": subclass_results,
        "pattern_summary": pattern_summary,
        "recommended_next_steps": next_steps,
        "next_steps": next_steps,
        "medical_disclaimer": MEDICAL_DISCLAIMER,
    }
